# This is a basic workflow to help you get started with Actions

name: Mail

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: print-diff
        shell: bash
        run: |
          sudo apt-get install bsd-mailx
          set smtp-use-starttls
          set nss-config-dir=/etc/pki/nss/
          set ssl-verify=ignore
          set smtp=smtp://smtp.gmail.com:587
          set smtp-auth=login
          set smtp-auth-user=akshay.shar2017@gmail.com
          set smtp-auth-password=akkiakki
          set from="akshay.shar2017@gmail.com"
          mailx -s "Subject line" akshay.shatr2019@gmail.com
      
