# This is a basic workflow to help you get started with Actions

name: Mail

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: print-diff
        shell: bash
        run: |
          #sudo apt-get install mailutils
          #sudo apt-get install libio-socket-ssl-perl
          #sudo apt-get install libnet-ssleay-perl
          sudo apt-get install sendemail
          sudo apt-get install libio-socket-ssl-perl
          sudo apt-get install libnet-ssleay-perl
          echo 'Akshay' > test.txt
          sendemail -l email.log -f "akshay.shar2021@gmail.com" -u "Email Subject 1" -t "akshay.shar20219@gmail.com" -s "smtp.gmail.com:587" -o tls=yes -xu "akshay.shar2021@gmail.com" -xp "akkiakki" -o message-file="test.txt"
