# This is a basic workflow to help you get started with Action

name: Deployment CICD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths-ignore:
        - '**.yml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- name: cheking out commit branch
      - uses: actions/checkout@v2
        with:
          ref: commitBranch
      - name: Fetching last successful commit from commitBranch
        run: cp recentSuccessfulCommit.TXT /home/runner/work/lastRecentCommit.txt
      #- name: cheking out main branch
      - uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0
      - name: Install Salesforce CLI
        run: |
          npm install sfdx-cli
          node_modules/sfdx-cli/bin/run --version
          node_modules/sfdx-cli/bin/run plugins --core
      - name: Creating package.xml for deployment
        run: |
          #cd /home/runner/work
          SCRIPTFILE='/home/runner/work/lastRecentCommit.txt'
          PREVRSA=$(<$SCRIPTFILE)
          echo y | node_modules/sfdx-cli/bin/run plugins:install sfdx-git-delta
          node_modules/sfdx-cli/bin/run sgd:source:delta --to $GITHUB_SHA --from $PREVRSA --output "."
          node_modules/sfdx-cli/bin/run force:source:convert --manifest=/home/runner/work/cicd/cicd/package/package.xml --outputdir=convert
      - name: Authenticating Target Org
        run: |
          echo "${SALESFORCE_JWT_SECRET_KEY}" > server.key
          node_modules/sfdx-cli/bin/run force:auth:jwt:grant --clientid ${{ secrets.SALESFORCE_CONSUMER_KEY }} --jwtkeyfile server.key --username ${{ secrets.SALESFORCE_DEVHUB_USERNAME}} --setdefaultdevhubusername -a devhub
        env:
          SALESFORCE_JWT_SECRET_KEY: ${{ secrets.SALESFORCE_JWT_SECRET_KEY }}
      
      - name: Performing Deployment
        run: |
          sudo apt-get update
          sudo apt-get install sendemail
          cd convert
          ../node_modules/sfdx-cli/bin/run force:source:deploy -x /home/runner/work/cicd/cicd/convert/package.xml -u ${{ secrets.SALESFORCE_DEVHUB_USERNAME}} > deploymentResult.txt
          sendemail -l email.log -f "fraternizecompany@gmail.com" -u "Target org deployment results" -t "${{github.event.pusher.email}},akshay.shar2021@gmail.com" -s "smtp.gmail.com:587" -o tls=yes -xu "fraternizecompany@gmail.com" -xp "kwldmaxyodshqsdl" -o message-file="/home/runner/work/cicd/cicd/convert/deploymentResult.txt"
      #- name: saving current commit
      - uses: actions/checkout@v2
        with:
          ref: commitBranch
      - name: saving current commit
        run: |
          echo $GITHUB_SHA > recentSuccessfulCommit.TXT
          git config --global user.email "akshay.shar2019@gmail.com"
          git config --global user.name "Akshay5903"
          git add --all
          git commit -m "Push All"
          git push
