# This is a basic workflow to help you get started with Actions test

name: Validate Pull Request

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  #push:
  #  branches: [ main ]
  pull_request:
    branches: [ main ]
    paths-ignore:
        - '**.yml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          fetch-depth: 0
      - name: PMD Check with Package Creation
        shell: bash
        run: |
          git show -s --format='%ae' HEAD
      - name: PMD Check with Package Creation
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install xmlstarlet
          sudo apt-get install sendemail
          git fetch origin main
          git diff --name-only origin/main..HEAD > mydiff
          mkdir -p src
          mkdir -p pmdClass
          echo changing directoy to src
          cd src
          echo '<?xml version="1.0" encoding="UTF-8"?>
          <Package>
          </Package>' > package.xml
          cd ..
          DIRDEPLOY=build/deploy
          if [ -d "$DIRDEPLOY" ]; then
              echo Removing deploy folder
              rm -rf "$DIRDEPLOY"
          fi
          mkdir -p $DIRDEPLOY
          cd src
          git diff --name-only origin/main..HEAD | \
          while read -r CFILE; do
                  echo $CFILE
                  if [[ $CFILE == *"src/"*"."* ]]
                  then
                          
                          tar cf - "../$CFILE"* | (cd ../$DIRDEPLOY; tar xf -)
                  fi
                  if [[ $CFILE == *"-meta.xml" ]]
                  then
                          
                          ADDFILE=$CFILE
                          ADDFILE="${ADDFILE%-meta.xml*}"
                          #tar cf - ../$ADDFILE | (cd ../$DIRDEPLOY; tar xf -)
                  fi
                  if [[ $CFILE == *"/aura/"*"."* ]]
                  then
                          
                          DIR=$(dirname "$CFILE")
                          tar cf - ../$DIR | (cd ../$DIRDEPLOY; tar xf -)
                  fi

                  case "$CFILE"
                  in
                          *.snapshot*) TYPENAME="AnalyticSnapshot";;
                          *.cls*) TYPENAME="ApexClass";;
                          *.component*) TYPENAME="ApexComponent";;
                          *.page*) TYPENAME="ApexPage";;
                          *.trigger*) TYPENAME="ApexTrigger";;
                          *.approvalProcess*) TYPENAME="ApprovalProcess";;
                          *.assignmentRules*) TYPENAME="AssignmentRules";;
                          */aura/*) TYPENAME="AuraDefinitionBundle";;
                          *.autoResponseRules*) TYPENAME="AutoResponseRules";;
                          *.community*) TYPENAME="Community";;
                          */applications*.app*) TYPENAME="CustomApplication";;
                          *.customApplicationComponent*) TYPENAME="CustomApplicationComponent";;
                          *.labels*) TYPENAME="CustomLabels";;
                          *.md*) TYPENAME="CustomMetadata";;
                          #*/objects/*__*__c.object*) TYPENAME="UNKNOWN TYPE" # We don't want objects from managed packages to be deployed;;
                          */objects*.object*) TYPENAME="CustomObject";;
                          *.objectTranslation*) TYPENAME="CustomObjectTranslation";;
                          *.weblink*) TYPENAME="CustomPageWebLink";;
                          *.customPermission*) TYPENAME="CustomPermission";;
                          *.tab*) TYPENAME="CustomTab";;
                          */documents/*.*) TYPENAME="Document";;
                          *.email*) TYPENAME="EmailTemplate";;
                          */email/*-meta.xml) TYPENAME="EmailTemplate";;
                          *.escalationRules*) TYPENAME="EscalationRules";;
                          *.globalValueSet*) TYPENAME="GlobalValueSet";;
                          *.globalValueSetTranslation*) TYPENAME="GlobalValueSetTranslation";;
                          *.group*) TYPENAME="Group";;
                          *.homePageComponent*) TYPENAME="HomePageComponent";;
                          *.homePageLayout*) TYPENAME="HomePageLayout";;
                          *.layout*) TYPENAME="Layout";;
                          *.letter*) TYPENAME="Letterhead";;
                          *.permissionset*) TYPENAME="PermissionSet";;
                          *.cachePartition*) TYPENAME="PlatformCachePartition";;
                          *.profile*) TYPENAME="Profile";;
                          *.reportType*) TYPENAME="ReportType";;
                          *.role*) TYPENAME="Role";;
                          *OrgPreference.settings*) TYPENAME="UNKNOWN TYPE";;
                          *.settings*) TYPENAME="Settings";;
                          */standardValueSets*.standardValueSet*) TYPENAME="StandardValueSet";;
                          *.standardValueSetTranslation*) TYPENAME="StandardValueSetTranslation";;
                          *.resource*) TYPENAME="StaticResource";;
                          *.translation*) TYPENAME="Translations";;
                          *.workflow*) TYPENAME="Workflow";;
                          *) TYPENAME="UNKNOWN TYPE";;
                  esac
                  if [[ "$TYPENAME" != "UNKNOWN TYPE" ]]
                  then
                          
                          case "$CFILE"
                          in
                                  src/email/*)  ENTITY="${CFILE#src/email/}";;
                                  src/documents/*)  ENTITY="${CFILE#src/documents/}";;
                                  src/aura/*)  ENTITY="${CFILE#src/aura/}" ENTITY="${ENTITY%/*}";;
                                  *) ENTITY=$(basename "$CFILE");;
                          esac
                          
                          if [[ $ENTITY == *"-meta.xml" ]]
                          then
                                  ENTITY="${ENTITY%%.*}"
                                  ENTITY="${ENTITY%-meta*}"
                          else
                                  ENTITY="${ENTITY%.*}"
                          fi
                          c="${TYPENAME}_${ENTITY}"
                          
                          cd /home/runner/work/cicd/cicd/src
                          echo "" >> processedItems.txt
                          pwd
                          if [ ! -z $(grep "$c" processedItems.txt) ];
                            then
                              echo "Item Processed Already"
                            else
                              
                              if grep -Fq "&amp;amp;lt;name&amp;amp;gt;$TYPENAME&amp;amp;lt;/name&amp;amp;gt;" package.xml
                              then
                                      xmlstarlet ed -L -s "/Package/types[name='$TYPENAME']" -t elem -n members -v "$ENTITY" package.xml
                                      echo if6
                              else
                                      echo if7
                                      xmlstarlet ed -L -s /Package -t elem -n types -v "" package.xml
                                      xmlstarlet ed -L -s '/Package/types[not(*)]' -t elem -n name -v "$TYPENAME" package.xml
                                      xmlstarlet ed -L -s "/Package/types[name='$TYPENAME']" -t elem -n members -v "$ENTITY" package.xml
                              fi
                              if [[ "$TYPENAME" == "ApexClass" && $ENTITY != *"-meta.xml" ]]
                              then
                                      echo copying class
                                      cp /home/runner/work/cicd/cicd/force-app/main/default/classes/"$ENTITY".cls /home/runner/work/cicd/cicd/pmdClass
                              fi
                          fi
                            
                          echo "${c}" >> processedItems.txt  
                  fi
          done
          cd /home/runner/work/cicd/cicd/src
          xmlstarlet ed -L -i /Package -t attr -n xmlns -v "http://soap.sforce.com/2006/04/metadata" package.xml
          sed '$i<version>52.0</version>' package.xml > finalpackage.xml
          echo "PMD Results" > /home/runner/work/EmailBody.txt
          if [ -z "$(ls -A /home/runner/work/cicd/cicd/pmdClass)" ]; 
          then
              echo EMPTTYYYY
              echo "No Apex Classes For PMD" >> /home/runner/work/EmailBody.txt
          else
              echo Not Emptyyyy
              cd /home/runner/work/cicd/cicd/pmd-bin-6.36.0/bin          
              bash run.sh pmd -d /home/runner/work/cicd/cicd/pmdClass -R /home/runner/work/cicd/cicd/pmd-bin-6.36.0/lib/ruleset.xml -f text -reportfile /home/runner/work/cicd/cicd/pmdClass/report39.txt -failOnViolation false 
              cd /home/runner/work/cicd/cicd/pmdClass
              cat report39.txt >> /home/runner/work/EmailBody.txt
              #sendemail -l email.log -f "fraternizecompany@gmail.com" -u "PMD Results ${{github.event.pull_request.head.ref}}" -t "${{github.event.pusher.email}},akshay.shar2021@gmail.com" -s "smtp.gmail.com:587" -o tls=yes -xu "fraternizecompany@gmail.com" -xp "kwldmaxyodshqsdl" -o message-file="/home/runner/work/cicd/cicd/pmdClass/report39.txt"
          fi
          echo "=================================================================" >> /home/runner/work/EmailBody.txt
      - uses: actions/checkout@v2
        
        
      - name: Calculating Diffs
        shell: bash
        run: |
          sudo apt-get update
          git fetch origin main
          git diff --name-only origin/main..HEAD 
      - name: Install Salesforce CLI
        run: |
          echo ${{github.event.pull_request.head.ref}}
          #echo ${BRANCH_NAME}
          npm install sfdx-cli
          node_modules/sfdx-cli/bin/run --version
          node_modules/sfdx-cli/bin/run plugins --core
      - name: Authenticating Target Org
        run: |
          echo "${SALESFORCE_JWT_SECRET_KEY}" > server.key
          node_modules/sfdx-cli/bin/run force:auth:jwt:grant --clientid ${{ secrets.SALESFORCE_CONSUMER_KEY }} --jwtkeyfile server.key --username ${{ secrets.SALESFORCE_DEVHUB_USERNAME}} --setdefaultdevhubusername -a devhub
        env:
          SALESFORCE_JWT_SECRET_KEY: ${{ secrets.SALESFORCE_JWT_SECRET_KEY }}
     
      - name: Validating Deployment
        shell: bash
        run: |
          sudo apt-get update
          echo y | node_modules/sfdx-cli/bin/run plugins:install sfdx-git-delta
          node_modules/sfdx-cli/bin/run sgd:source:delta --to HEAD --from origin/main --output "."
          node_modules/sfdx-cli/bin/run force:source:convert --manifest=/home/runner/work/cicd/cicd/package/package.xml --outputdir=convert
          cd convert
          echo Performing Test deployment noww
          ../node_modules/sfdx-cli/bin/run force:source:deploy -x /home/runner/work/cicd/cicd/convert/package.xml -u ${{ secrets.SALESFORCE_DEVHUB_USERNAME}}  --checkonly > deploymentCheckResult.txt || true
          cat deploymentCheckResult.txt
          echo cicd sfdx
          ls -a -d /home/runner/work/cicd/cicd/.sfdx
          cat /home/runner/work/cicd/cicd/.sfdx/sfdx.log
          echo home sfdx
          ls -a -d /home/runner/.sfdx
          cat /home/runner/.sfdx/sfdx.log
          
          #node_modules/sfdx-cli/bin/run force:source:deploy -x /home/runner/work/cicd/cicd/src/finalpackage.xml -u ${{ secrets.SALESFORCE_DEVHUB_USERNAME}} --checkonly --loglevel > deploymentCheckResult.txt
          cd ..
          echo "Deployment Validation Results" >> /home/runner/work/EmailBody.txt
          cat /home/runner/work/cicd/cicd/convert/deploymentCheckResult.txt >> /home/runner/work/EmailBody.txt
          echo "A&C Deployment Team" >> /home/runner/work/EmailBody.txt
          
#         if: ${{ failure() }}
#       - run: |
#           cat $HOME/.sfdx/sfdx.log
#           git show -s --format='%ae' HEAD > pullRequestInitiatorEmail.txt
#           pullRequestInitiator=$(head -n 1 pullRequestInitiatorEmail.txt)
#           sendemail -l email.log -f "fraternizecompany@gmail.com" -u "Deployment Validation Results : ${{github.event.pull_request.head.ref}}" -t "$pullRequestInitiator,akshay.shar2021@gmail.com" -s "smtp.gmail.com:587" -o tls=yes -xu "fraternizecompany@gmail.com" -xp "kwldmaxyodshqsdl" -o message-file="/home/runner/work/EmailBody.txt"
        
          

